# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install
          # run a custom app build step
          # build: 'npm install'
      - cypress/run:
          requires:
              - cypress/install
          executor: cypress/base-14
          command: npx cypress run cy_open:u1
          parallel: true
          parallelism: 2
          group: 2 machines
