version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install
      # run a custom app build step
      # build: 'npm install'
      - cypress/run:
          name: Chrome test run
          executor: cypress/browsers-chrome86-ff82
          requires:
            - cypress/install
          command: npm run test:qa_env_1
          browser: chrome
          parallel: true
          parallelism: 2
          group: Chrome (2 machines)
      - cypress/run:
          name: FireFox test run
          executor: cypress/browsers-chrome86-ff82
          requires:
            - cypress/install
          command: npm run test:qa_env_2
          browser: firefox
          parallel: true
          parallelism: 2
          group: FireFox (2 machines)
