version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install
          # run a custom app build step
          # build: 'npm install'
      - cypress/run:
          requires:
              - cypress/install
          executor: cypress/base-14
          command: npx cypress run cy_open:u1
          parallel: true
          parallelism: 2
          group: 2 machines
